version: "3.9"
    
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
       POSTGRES_DB: crud_live
       POSTGRES_USER: live
       POSTGRES_PASSWORD: 1234
    restart: "no"
    ports:
        - "5432:5432"
    deploy:
        resources:
            limits:
                cpus: "1"
                memory: "500MB"
